const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirts',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numRewviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Adidas Fit Shirts',
            category:'Shirts',
            image:'/images/p2.jpg',
            price:100,
            brand:'Adidas',
            rating:4,
            numRewviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Lacoste Free Shirts',
            category:'Shirts',
            image:'/images/p3.jpg',
            price:220,
            brand:'Lacoste',
            rating:4.8,
            numRewviews:17,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Nike Slim Pant',
            category:'Pants',
            image:'/images/p4.jpg',
            price:180,
            brand:'Nike',
            rating:4.6,
            numRewviews:20,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Puma slim Pant',
            category:'Pants',
            image:'/images/p5.jpg',
            price:80,
            brand:'Puma',
            rating:4.1,
            numRewviews:15,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Adidas Fit Pant',
            category:'Pants',
            image:'/images/p6.jpg',
            price:89,
            brand:'Nike',
            rating:4.7,
            numRewviews:10,
            description:'high quality product',
        },
    ],
};
export default data;